version: '3.8'

services:
  redis:
    image: 'bitnami/redis:6.2.14'
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    networks:
      - recebiveis-api
        
  recebiveis-backend:
    image: node:20.9
    container_name: recebiveis-backend
    working_dir: /api
    command: sh -c "npm run start:dev"
    build:
      context: .
    ports:
      - '3001:3001'
    volumes:
      - .:/api
    networks:
      - recebiveis-api

networks:
  recebiveis-api:
    name: recebiveis-api
    external: true
