version: '3.8'

services:
  app:
    container_name: app
    working_dir: /app
    command: sh -c "npm run start:dev"
    build:
      context: .
    ports:
      - '${PORT:-3000}:3000'
    volumes:
      - .:/app